name = "oh-my-git-web-nuxt"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".output/public"

# D1 schema is kept under server/database/migrations for future migration.
# Current Cloudflare deployment uses KV because the account has reached the D1 database limit.

[[kv_namespaces]]
binding = "KV"
id = "7f89e97b4e0e40d68f95d210c2d39b1f"
