name = "oh-my-git-web-next"
main = ".open-next/worker.js"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]
keep_vars = true
preview_urls = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "KV"
id = "7f89e97b4e0e40d68f95d210c2d39b1f"
